<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Login: Slim Bookshelf</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/pure-min.css">
        <link rel="stylesheet" href="/style.css">
    </head>
    <body>
        <div class="pure-g">
            <div class="pure-u-1 l-box">
                <div class="pure-menu pure-menu-horizontal">
                    <ul class="pure-menu-list">
                        <li class="pure-menu-item"><a href="/" class="pure-menu-link">Home</a></li>
                        <?php if ($username) : ?>
                        <li class="pure-menu-item"><a href="/logout" class="pure-menu-link">Log out</a></li>
                        <li class="pure-menu-item pure-menu-item-separator"></li>
                        <li class="pure-menu-item pure-menu-disabled">Logged in as <?= htmlentities($username) ?></li>
                        <?php endif; ?>
                    </ul>
                </div>
