<?php include __DIR__ . '/header.inc.phtml' ?>

<h1>Log in</h1>

<?php if ($error) : ?>
    <p class="error"><?= htmlentities($error) ?></p>
<?php endif; ?>
<form method="POST" class="pure-form pure-form-stacked">

    <label for="username">Username</label>
    <input type="text" name="username" id="username" required value="rob">

    <label for="password">Password</label>
    <input type="password" name="password" id="password" required value="123456">

    <button type="submit" class="pure-button pure-button-primary">Sign in</button>

</form>

<?php include __DIR__ . '/footer.inc.phtml' ?>
